[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "#FAB387"
index = 16

[[colors.indexed_colors]]
color = "#F5E0DC"
index = 17

[colors.bright]
black = "#585B70"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#A6ADC8"
yellow = "#F9E2AF"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#45475A"
blue = "#89B4FA"
cyan = "#94E2D5"
green = "#A6E3A1"
magenta = "#F5C2E7"
red = "#F38BA8"
white = "#BAC2DE"
yellow = "#F9E2AF"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

# [colors.search.footer_bar]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

# [[schemes.Catppuccin-Macchiato.indexed_colors]]
# color = "#F5A97F"
# index = 16
#
# [[schemes.Catppuccin-Macchiato.indexed_colors]]
# color = "#F4DBD6"
# index = 17
#
# [schemes.Catppuccin-Macchiato.bright]
# black = "#5B6078"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#A5ADCB"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.cursor]
# cursor = "#F4DBD6"
# text = "#24273A"
#
# [schemes.Catppuccin-Macchiato.dim]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.hints.end]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.hints.start]
# background = "#EED49F"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.normal]
# black = "#494D64"
# blue = "#8AADF4"
# cyan = "#8BD5CA"
# green = "#A6DA95"
# magenta = "#F5BDE6"
# red = "#ED8796"
# white = "#B8C0E0"
# yellow = "#EED49F"
#
# [schemes.Catppuccin-Macchiato.primary]
# background = "#24273A"
# bright_foreground = "#CAD3F5"
# dim_foreground = "#CAD3F5"
# foreground = "#CAD3F5"
#
# [schemes.Catppuccin-Macchiato.search.focused_match]
# background = "#A6DA95"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.search.footer_bar]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.search.matches]
# background = "#A5ADCB"
# foreground = "#24273A"
#
# [schemes.Catppuccin-Macchiato.selection]
# background = "#F4DBD6"
# text = "#24273A"
#
# [schemes.Catppuccin-Macchiato.vi_mode_cursor]
# cursor = "#B7BDF8"
# text = "#24273A"
#
# [[schemes.Catppuccin-Mocha.indexed_colors]]
# color = "#FAB387"
# index = 16
#
# [[schemes.Catppuccin-Mocha.indexed_colors]]
# color = "#F5E0DC"
# index = 17
#
# [schemes.Catppuccin-Mocha.bright]
# black = "#585B70"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#A6ADC8"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.cursor]
# cursor = "#F5E0DC"
# text = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.dim]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.hints.end]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.hints.start]
# background = "#F9E2AF"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.normal]
# black = "#45475A"
# blue = "#89B4FA"
# cyan = "#94E2D5"
# green = "#A6E3A1"
# magenta = "#F5C2E7"
# red = "#F38BA8"
# white = "#BAC2DE"
# yellow = "#F9E2AF"
#
# [schemes.Catppuccin-Mocha.primary]
# background = "#1E1E2E"
# bright_foreground = "#CDD6F4"
# dim_foreground = "#CDD6F4"
# foreground = "#CDD6F4"
#
# [schemes.Catppuccin-Mocha.search.focused_match]
# background = "#A6E3A1"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.search.footer_bar]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.search.matches]
# background = "#A6ADC8"
# foreground = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.selection]
# background = "#F5E0DC"
# text = "#1E1E2E"
#
# [schemes.Catppuccin-Mocha.vi_mode_cursor]
# cursor = "#B4BEFE"
# text = "#1E1E2E"
#
[scrolling]
history = 50000

[window]
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 3
y = 3
