#!/bin/bash

### Default Style
# CONFIG="$HOME/.config/hypr/waybar/catppuccin/config"
# STYLE="$HOME/.config/hypr/waybar/catppuccin/style.css"

### Style 2
CONFIG="$HOME/.config/hypr/waybar/bar2/config"
STYLE="$HOME/.config/hypr/waybar/bar2/style.css"
if [[ ! $(pidof waybar) ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
