vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrw = 1
vim.opt.shiftwidth = 2
vim.opt.number = true
vim.opt.clipboard = "unnamedplus"
vim.o.hlsearch = false
vim.o.mouse = 'a'
vim.o.undofile = true
vim.o.smartcase = true
vim.o.termguicolors = true
vim.opt.colorcolumn = "80"
vim.wo.signcolumn = 'yes'
vim.opt.shiftwidth = 4
vim.o.updatetime = 250
vim.o.timeoutlen = 300
vim.o.hlsearch = false
vim.o.foldcolumn = '0' -- '0' is not bad
vim.o.foldlevel = 99   -- Using ufo provider need a large value, feel free to decrease the value
vim.o.foldlevelstart = 99
vim.o.foldenable = true
vim.o.breakindent = true
